version: '3'
services:
  first-vue:
    container_name: first-vue
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run serve
    tty: true